# Generated by Django 2.1.5 on 2019-02-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('caracteristicas', models.TextField(max_length=500)),
                ('observacion', models.TextField(max_length=300)),
                ('serial', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateTimeField(verbose_name='Fecha de Ingreso')),
                ('estado', models.CharField(choices=[('actv', 'Activo'), ('dctv', 'Inactivo')], default='actv', max_length=4)),
            ],
        ),
    ]
