# Generated by Django 2.1.5 on 2019-02-06 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.CharField(max_length=200)),
                ('materia', models.CharField(max_length=200)),
                ('seccion', models.IntegerField(default=0)),
                ('entrada', models.TimeField(verbose_name='Hora Entrada')),
                ('salida', models.TimeField(verbose_name='Hora Salida')),
                ('asistio', models.BooleanField(default=True)),
                ('laboratorio_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Laboratorio')),
            ],
        ),
    ]
