# Generated by Django 2.1.5 on 2019-01-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.CharField(max_length=200)),
                ('materia', models.CharField(max_length=200)),
                ('dia', models.DateTimeField(verbose_name='Fecha asistencia')),
            ],
        ),
    ]
